constdata = [
  {
    Route_ID: 1,
    sample_no: 4,
    sample_area: 152,
    Survey_Responsible: "Mohamed Ahmed",
    Alligator_crack: null,
    Alligator_crack_power: null,
    Alligator_crack_area: null,
    Bleeding: true,
    Bleeding_power: 1,
    Bleeding_area: "50",
    Blocking_cracks: null,
    Blocking_cracks_power: null,
    Blocking_cracks_area: "",
    Edge_cracking: null,
    Edge_cracking_powe: null,
    Edge_cracking_area: null,
    Rutting: null,
    Rutting_power: null,
    Rutting_area: null,
    Long_Trans: null,
    Long_Trans_power: null,
    Long_Trans_area: null,
    Comment: "",
    Images: "",
    Entry_Date: "5/20/2020",
    Data_Entry_Responsible: "Nada",
    FIELD27: "",
  },
  {
    Route_ID: 2,
    sample_no: 5,
    sample_area: 130,
    Survey_Responsible: "Mohamed Ahmed",
    Alligator_crack: null,
    Alligator_crack_power: null,
    Alligator_crack_area: null,
    Bleeding: null,
    Bleeding_power: null,
    Bleeding_area: "",
    Blocking_cracks: null,
    Blocking_cracks_power: null,
    Blocking_cracks_area: "",
    Edge_cracking: null,
    Edge_cracking_powe: null,
    Edge_cracking_area: null,
    Rutting: true,
    Rutting_power: 2,
    Rutting_area: 96,
    Long_Trans: null,
    Long_Trans_power: null,
    Long_Trans_area: null,
    Comment: "",
    Images: "",
    Entry_Date: "5/21/2020",
    Data_Entry_Responsible: "Mona",
    FIELD27: "",
  },
  {
    Route_ID: 3,
    sample_no: 6,
    sample_area: 260,
    Survey_Responsible: "AhmedMohamed",
    Alligator_crack: null,
    Alligator_crack_power: null,
    Alligator_crack_area: null,
    Bleeding: null,
    Bleeding_power: null,
    Bleeding_area: "TRUE",
    Blocking_cracks: 3,
    Blocking_cracks_power: 135,
    Blocking_cracks_area: "",
    Edge_cracking: null,
    Edge_cracking_powe: null,
    Edge_cracking_area: null,
    Rutting: null,
    Rutting_power: null,
    Rutting_area: null,
    Long_Trans: null,
    Long_Trans_power: null,
    Long_Trans_area: null,
    Comment: "",
    Images: "",
    Entry_Date: "5/22/2020",
    Data_Entry_Responsible: "Hala",
    FIELD27: "",
  },
  {
    Route_ID: 4,
    sample_no: 3,
    sample_area: 300,
    Survey_Responsible: "Azza Atef",
    Alligator_crack: true,
    Alligator_crack_power: 3,
    Alligator_crack_area: 140,
    Bleeding: null,
    Bleeding_power: null,
    Bleeding_area: "",
    Blocking_cracks: null,
    Blocking_cracks_power: null,
    Blocking_cracks_area: "",
    Edge_cracking: null,
    Edge_cracking_powe: null,
    Edge_cracking_area: null,
    Rutting: null,
    Rutting_power: null,
    Rutting_area: null,
    Long_Trans: null,
    Long_Trans_power: null,
    Long_Trans_area: null,
    Comment: "",
    Images: "",
    Entry_Date: "5/23/2020",
    Data_Entry_Responsible: "Hala",
    FIELD27: "",
  },
  {
    Route_ID: 6,
    sample_no: 2,
    sample_area: 172,
    Survey_Responsible: "Mai Rabea",
    Alligator_crack: null,
    Alligator_crack_power: null,
    Alligator_crack_area: null,
    Bleeding: null,
    Bleeding_power: null,
    Bleeding_area: "",
    Blocking_cracks: null,
    Blocking_cracks_power: null,
    Blocking_cracks_area: "",
    Edge_cracking: true,
    Edge_cracking_powe: 2,
    Edge_cracking_area: 100,
    Rutting: null,
    Rutting_power: null,
    Rutting_area: null,
    Long_Trans: null,
    Long_Trans_power: null,
    Long_Trans_area: null,
    Comment: "",
    Images: "",
    Entry_Date: "5/24/2020",
    Data_Entry_Responsible: "Aya",
    FIELD27: "",
  },
  {
    Route_ID: 6,
    sample_no: 1,
    sample_area: 324,
    Survey_Responsible: "Mai Rabea",
    Alligator_crack: true,
    Alligator_crack_power: 3,
    Alligator_crack_area: 130,
    Bleeding: null,
    Bleeding_power: null,
    Bleeding_area: "",
    Blocking_cracks: null,
    Blocking_cracks_power: null,
    Blocking_cracks_area: "",
    Edge_cracking: null,
    Edge_cracking_powe: null,
    Edge_cracking_area: null,
    Rutting: null,
    Rutting_power: null,
    Rutting_area: null,
    Long_Trans: null,
    Long_Trans_power: null,
    Long_Trans_area: null,
    Comment: "",
    Images: "imgurl",
    Entry_Date: "5/25/2020",
    Data_Entry_Responsible: "Mohamed",
    FIELD27: "",
  },
  {
    Route_ID: 7,
    sample_no: 7,
    sample_area: 120,
    Survey_Responsible: "Asmaa Abdelmonem",
    Alligator_crack: null,
    Alligator_crack_power: null,
    Alligator_crack_area: null,
    Bleeding: null,
    Bleeding_power: null,
    Bleeding_area: "",
    Blocking_cracks: null,
    Blocking_cracks_power: null,
    Blocking_cracks_area: "",
    Edge_cracking: null,
    Edge_cracking_powe: null,
    Edge_cracking_area: null,
    Rutting: null,
    Rutting_power: null,
    Rutting_area: null,
    Long_Trans: true,
    Long_Trans_power: 1,
    Long_Trans_area: 60,
    Comment: "",
    Images: "",
    Entry_Date: "5/26/2020",
    Data_Entry_Responsible: "Mona",
    FIELD27: "",
  },
  {
    Route_ID: 8,
    sample_no: 6,
    sample_area: 75,
    Survey_Responsible: "Zeinab ayman",
    Alligator_crack: true,
    Alligator_crack_power: 2,
    Alligator_crack_area: 102,
    Bleeding: null,
    Bleeding_power: null,
    Bleeding_area: "",
    Blocking_cracks: null,
    Blocking_cracks_power: null,
    Blocking_cracks_area: "",
    Edge_cracking: null,
    Edge_cracking_powe: null,
    Edge_cracking_area: null,
    Rutting: null,
    Rutting_power: null,
    Rutting_area: null,
    Long_Trans: null,
    Long_Trans_power: null,
    Long_Trans_area: null,
    Comment: "",
    Images: "",
    Entry_Date: "5/27/2020",
    Data_Entry_Responsible: "Mai",
    FIELD27: "",
  },
  {
    Route_ID: null,
    sample_no: null,
    sample_area: null,
    Survey_Responsible: "",
    Alligator_crack: null,
    Alligator_crack_power: null,
    Alligator_crack_area: null,
    Bleeding: null,
    Bleeding_power: null,
    Bleeding_area: "",
    Blocking_cracks: null,
    Blocking_cracks_power: null,
    Blocking_cracks_area: "",
    Edge_cracking: null,
    Edge_cracking_powe: null,
    Edge_cracking_area: null,
    Rutting: null,
    Rutting_power: null,
    Rutting_area: null,
    Long_Trans: null,
    Long_Trans_power: null,
    Long_Trans_area: null,
    Comment: "",
    Images: "",
    Entry_Date: "",
    Data_Entry_Responsible: "Hala",
    FIELD27: "",
  },
];
