const data = [
  {
    Intersection_ID: 1,
    Id: 6,
    Survey_No: 1,
    Collected_Date: "5/26/2020",
    Survey_Responsible: "equipment no1",
    Alligator_crack: "not exists",
    Alligator_crack_power: "not exists",
    Alligator_crack_area: "not exists",
    Bleeding: "true",
    Bleeding_power: 1,
    Bleeding_area: "50",
    Blocking_cracks: "not exists",
    Blocking_cracks_power: "not exists",
    Blocking_cracks_area: "",
    Edge_cracking: "not exists",
    Edge_cracking_powe: "not exists",
    Edge_cracking_area: "not exists",
    Rutting: "not exists",
    Rutting_power: "not exists",
    Rutting_area: "not exists",
    Long_Trans: "not exists",
    Long_Trans_power: "not exists",
    Long_Trans_area: "not exists",
    Comment: "",
    Images: "",
    Entry_Date: "6/3/2020",
    Data_Entry_Responsible: "Mai Rabea",
  },
  {
    Intersection_ID: 2,
    Id: 7,
    Survey_No: 2,
    Collected_Date: "5/26/2020",
    Survey_Responsible: "equipment no1",
    Alligator_crack: "not exists",
    Alligator_crack_power: "not exists",
    Alligator_crack_area: "not exists",
    Bleeding: "not exists",
    Bleeding_power: "not exists",
    Bleeding_area: "",
    Blocking_cracks: "not exists",
    Blocking_cracks_power: "not exists",
    Blocking_cracks_area: "",
    Edge_cracking: "not exists",
    Edge_cracking_powe: "not exists",
    Edge_cracking_area: "not exists",
    Rutting: "true",
    Rutting_power: 2,
    Rutting_area: 96,
    Long_Trans: "not exists",
    Long_Trans_power: "not exists",
    Long_Trans_area: "not exists",
    Comment: "",
    Images: "imgurl",
    Entry_Date: "6/4/2020",
    Data_Entry_Responsible: "Mai Rabea",
  },
  {
    Intersection_ID: 3,
    Id: 8,
    Survey_No: 3,
    Collected_Date: "5/26/2020",
    Survey_Responsible: "equipment no1",
    Alligator_crack: "not exists",
    Alligator_crack_power: "not exists",
    Alligator_crack_area: "not exists",
    Bleeding: "not exists",
    Bleeding_power: "not exists",
    Bleeding_area: "true",
    Blocking_cracks: 3,
    Blocking_cracks_power: 135,
    Blocking_cracks_area: "",
    Edge_cracking: "not exists",
    Edge_cracking_powe: "not exists",
    Edge_cracking_area: "not exists",
    Rutting: "not exists",
    Rutting_power: "not exists",
    Rutting_area: "not exists",
    Long_Trans: "not exists",
    Long_Trans_power: "not exists",
    Long_Trans_area: "not exists",
    Comment: "",
    Images: "",
    Entry_Date: "6/5/2020",
    Data_Entry_Responsible: "Azza Atef",
  },
  {
    Intersection_ID: 4,
    Id: 1,
    Survey_No: 4,
    Collected_Date: "5/29/2020",
    Survey_Responsible: "equipment no2",
    Alligator_crack: "true",
    Alligator_crack_power: 3,
    Alligator_crack_area: 140,
    Bleeding: "not exists",
    Bleeding_power: "not exists",
    Bleeding_area: "",
    Blocking_cracks: "not exists",
    Blocking_cracks_power: "not exists",
    Blocking_cracks_area: "",
    Edge_cracking: "not exists",
    Edge_cracking_powe: "not exists",
    Edge_cracking_area: "not exists",
    Rutting: "not exists",
    Rutting_power: "not exists",
    Rutting_area: "not exists",
    Long_Trans: "not exists",
    Long_Trans_power: "not exists",
    Long_Trans_area: "not exists",
    Comment: "",
    Images: "",
    Entry_Date: "6/6/2020",
    Data_Entry_Responsible: "Azza Atef",
  },
  {
    Intersection_ID: 5,
    Id: 2,
    Survey_No: 5,
    Collected_Date: "5/30/2020",
    Survey_Responsible: "equipment no3",
    Alligator_crack: "not exists",
    Alligator_crack_power: "not exists",
    Alligator_crack_area: "not exists",
    Bleeding: "not exists",
    Bleeding_power: "not exists",
    Bleeding_area: "",
    Blocking_cracks: "not exists",
    Blocking_cracks_power: "not exists",
    Blocking_cracks_area: "",
    Edge_cracking: "true",
    Edge_cracking_powe: 2,
    Edge_cracking_area: 100,
    Rutting: "not exists",
    Rutting_power: "not exists",
    Rutting_area: "not exists",
    Long_Trans: "not exists",
    Long_Trans_power: "not exists",
    Long_Trans_area: "not exists",
    Comment: "",
    Images: "",
    Entry_Date: "6/7/2020",
    Data_Entry_Responsible: "Azza Atef",
  },
  {
    Intersection_ID: 6,
    Id: 3,
    Survey_No: 6,
    Collected_Date: "5/31/2020",
    Survey_Responsible: "equipment no4",
    Alligator_crack: "true",
    Alligator_crack_power: 3,
    Alligator_crack_area: 130,
    Bleeding: "not exists",
    Bleeding_power: "not exists",
    Bleeding_area: "",
    Blocking_cracks: "not exists",
    Blocking_cracks_power: "not exists",
    Blocking_cracks_area: "",
    Edge_cracking: "not exists",
    Edge_cracking_powe: "not exists",
    Edge_cracking_area: "not exists",
    Rutting: "not exists",
    Rutting_power: "not exists",
    Rutting_area: "not exists",
    Long_Trans: "not exists",
    Long_Trans_power: "not exists",
    Long_Trans_area: "not exists",
    Comment: "",
    Images: "",
    Entry_Date: "6/8/2020",
    Data_Entry_Responsible: "Azza Atef",
  },
  {
    Intersection_ID: 7,
    Id: 4,
    Survey_No: 7,
    Collected_Date: "6/1/2020",
    Survey_Responsible: "equipment no5",
    Alligator_crack: "not exists",
    Alligator_crack_power: "not exists",
    Alligator_crack_area: "not exists",
    Bleeding: "not exists",
    Bleeding_power: "not exists",
    Bleeding_area: "",
    Blocking_cracks: "not exists",
    Blocking_cracks_power: "not exists",
    Blocking_cracks_area: "",
    Edge_cracking: "not exists",
    Edge_cracking_powe: "not exists",
    Edge_cracking_area: "not exists",
    Rutting: "not exists",
    Rutting_power: "not exists",
    Rutting_area: "not exists",
    Long_Trans: "true",
    Long_Trans_power: 1,
    Long_Trans_area: 60,
    Comment: "",
    Images: "",
    Entry_Date: "6/9/2020",
    Data_Entry_Responsible: "Mai Rabea",
  },
  {
    Intersection_ID: 8,
    Id: 5,
    Survey_No: 8,
    Collected_Date: "6/2/2020",
    Survey_Responsible: "equipment no6",
    Alligator_crack: "true",
    Alligator_crack_power: 2,
    Alligator_crack_area: 102,
    Bleeding: "not exists",
    Bleeding_power: "not exists",
    Bleeding_area: "",
    Blocking_cracks: "not exists",
    Blocking_cracks_power: "not exists",
    Blocking_cracks_area: "",
    Edge_cracking: "not exists",
    Edge_cracking_powe: "not exists",
    Edge_cracking_area: "not exists",
    Rutting: "not exists",
    Rutting_power: "not exists",
    Rutting_area: "not exists",
    Long_Trans: "not exists",
    Long_Trans_power: "not exists",
    Long_Trans_area: "not exists",
    Comment: "",
    Images: "",
    Entry_Date: "6/10/2020",
    Data_Entry_Responsible: "Mai Rabea",
  },
  {
    Intersection_ID: "not exists",
    Id: "not exists",
    Survey_No: "not exists",
    Collected_Date: "",
    Survey_Responsible: "",
    Alligator_crack: "not exists",
    Alligator_crack_power: "not exists",
    Alligator_crack_area: "not exists",
    Bleeding: "not exists",
    Bleeding_power: "not exists",
    Bleeding_area: "",
    Blocking_cracks: "not exists",
    Blocking_cracks_power: "not exists",
    Blocking_cracks_area: "",
    Edge_cracking: "not exists",
    Edge_cracking_powe: "not exists",
    Edge_cracking_area: "not exists",
    Rutting: "not exists",
    Rutting_power: "not exists",
    Rutting_area: "not exists",
    Long_Trans: "not exists",
    Long_Trans_power: "not exists",
    Long_Trans_area: "not exists",
    Comment: "",
    Images: "",
    Entry_Date: "",
    Data_Entry_Responsible: "",
  },
  {
    Intersection_ID: "not exists",
    Id: "not exists",
    Survey_No: "not exists",
    Collected_Date: "",
    Survey_Responsible: "",
    Alligator_crack: "not exists",
    Alligator_crack_power: "not exists",
    Alligator_crack_area: "not exists",
    Bleeding: "not exists",
    Bleeding_power: "not exists",
    Bleeding_area: "",
    Blocking_cracks: "not exists",
    Blocking_cracks_power: "not exists",
    Blocking_cracks_area: "",
    Edge_cracking: "not exists",
    Edge_cracking_powe: "not exists",
    Edge_cracking_area: "not exists",
    Rutting: "not exists",
    Rutting_power: "not exists",
    Rutting_area: "not exists",
    Long_Trans: "not exists",
    Long_Trans_power: "not exists",
    Long_Trans_area: "not exists",
    Comment: "",
    Images: "",
    Entry_Date: "",
    Data_Entry_Responsible: "",
  },
  {
    Intersection_ID: "not exists",
    Id: "not exists",
    Survey_No: "not exists",
    Collected_Date: "",
    Survey_Responsible: "",
    Alligator_crack: "not exists",
    Alligator_crack_power: "not exists",
    Alligator_crack_area: "not exists",
    Bleeding: "not exists",
    Bleeding_power: "not exists",
    Bleeding_area: "",
    Blocking_cracks: "not exists",
    Blocking_cracks_power: "not exists",
    Blocking_cracks_area: "",
    Edge_cracking: "not exists",
    Edge_cracking_powe: "not exists",
    Edge_cracking_area: "not exists",
    Rutting: "not exists",
    Rutting_power: "not exists",
    Rutting_area: "not exists",
    Long_Trans: "not exists",
    Long_Trans_power: "not exists",
    Long_Trans_area: "not exists",
    Comment: "",
    Images: "",
    Entry_Date: "",
    Data_Entry_Responsible: "",
  },
  {
    Intersection_ID: "not exists",
    Id: "not exists",
    Survey_No: "not exists",
    Collected_Date: "",
    Survey_Responsible: "",
    Alligator_crack: "not exists",
    Alligator_crack_power: "not exists",
    Alligator_crack_area: "not exists",
    Bleeding: "not exists",
    Bleeding_power: "not exists",
    Bleeding_area: "",
    Blocking_cracks: "not exists",
    Blocking_cracks_power: "not exists",
    Blocking_cracks_area: "",
    Edge_cracking: "not exists",
    Edge_cracking_powe: "not exists",
    Edge_cracking_area: "not exists",
    Rutting: "not exists",
    Rutting_power: "not exists",
    Rutting_area: "not exists",
    Long_Trans: "not exists",
    Long_Trans_power: "not exists",
    Long_Trans_area: "not exists",
    Comment: "",
    Images: "",
    Entry_Date: "",
    Data_Entry_Responsible: "",
  },
  {
    Intersection_ID: "not exists",
    Id: "not exists",
    Survey_No: "not exists",
    Collected_Date: "",
    Survey_Responsible: "",
    Alligator_crack: "not exists",
    Alligator_crack_power: "not exists",
    Alligator_crack_area: "not exists",
    Bleeding: "not exists",
    Bleeding_power: "not exists",
    Bleeding_area: "",
    Blocking_cracks: "not exists",
    Blocking_cracks_power: "not exists",
    Blocking_cracks_area: "",
    Edge_cracking: "not exists",
    Edge_cracking_powe: "not exists",
    Edge_cracking_area: "not exists",
    Rutting: "not exists",
    Rutting_power: "not exists",
    Rutting_area: "not exists",
    Long_Trans: "not exists",
    Long_Trans_power: "not exists",
    Long_Trans_area: "not exists",
    Comment: "",
    Images: "",
    Entry_Date: "",
    Data_Entry_Responsible: "",
  },
  {
    Intersection_ID: "not exists",
    Id: "not exists",
    Survey_No: "not exists",
    Collected_Date: "",
    Survey_Responsible: "",
    Alligator_crack: "not exists",
    Alligator_crack_power: "not exists",
    Alligator_crack_area: "not exists",
    Bleeding: "not exists",
    Bleeding_power: "not exists",
    Bleeding_area: "",
    Blocking_cracks: "not exists",
    Blocking_cracks_power: "not exists",
    Blocking_cracks_area: "",
    Edge_cracking: "not exists",
    Edge_cracking_powe: "not exists",
    Edge_cracking_area: "not exists",
    Rutting: "not exists",
    Rutting_power: "not exists",
    Rutting_area: "not exists",
    Long_Trans: "not exists",
    Long_Trans_power: "not exists",
    Long_Trans_area: "not exists",
    Comment: "",
    Images: "",
    Entry_Date: "",
    Data_Entry_Responsible: "",
  },
  {
    Intersection_ID: "not exists",
    Id: "not exists",
    Survey_No: "not exists",
    Collected_Date: "",
    Survey_Responsible: "",
    Alligator_crack: "not exists",
    Alligator_crack_power: "not exists",
    Alligator_crack_area: "not exists",
    Bleeding: "not exists",
    Bleeding_power: "not exists",
    Bleeding_area: "",
    Blocking_cracks: "not exists",
    Blocking_cracks_power: "not exists",
    Blocking_cracks_area: "",
    Edge_cracking: "not exists",
    Edge_cracking_powe: "not exists",
    Edge_cracking_area: "not exists",
    Rutting: "not exists",
    Rutting_power: "not exists",
    Rutting_area: "not exists",
    Long_Trans: "not exists",
    Long_Trans_power: "not exists",
    Long_Trans_area: "not exists",
    Comment: "",
    Images: "",
    Entry_Date: "",
    Data_Entry_Responsible: "",
  },
];
