const Data = [
  {
    OBJECTID: 1,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.834946,
    sampleId: 50,
  },
  {
    OBJECTID: 8,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.8368,
    sampleId: 1,
  },
  {
    OBJECTID: 9,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.61019,
    sampleId: 1,
  },
  {
    OBJECTID: 10,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.14441,
    sampleId: 2,
  },
  {
    OBJECTID: 11,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.571785,
    sampleId: 1,
  },
  {
    OBJECTID: 12,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.30379,
    sampleId: 10,
  },
  {
    OBJECTID: 13,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.81402,
    sampleId: 1,
  },
  {
    OBJECTID: 14,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.45036,
    sampleId: 2,
  },
  {
    OBJECTID: 15,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 2,
    Shape_Length: 100.20556,
    sampleId: 1,
  },
  {
    OBJECTID: 16,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 2,
    Shape_Length: 100.03744,
    sampleId: 2,
  },
  {
    OBJECTID: 17,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 3,
    Shape_Length: 98.64218,
    sampleId: 1,
  },
  {
    OBJECTID: 19,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 3,
    Shape_Length: 98.31883,
    sampleId: 2,
  },
  {
    OBJECTID: 20,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.83836,
    sampleId: 1,
  },
  {
    OBJECTID: 22,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 1,
    Shape_Length: 100.26467,
    sampleId: 1,
  },
  {
    OBJECTID: 23,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 1,
    Shape_Length: 100.74722,
    sampleId: 2,
  },
  {
    OBJECTID: 24,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42734,
    sampleId: 2,
  },
  {
    OBJECTID: 28,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 1,
    Shape_Length: 107.53821,
    sampleId: 1,
  },
  {
    OBJECTID: 29,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 1,
    Shape_Length: 107.119965,
    sampleId: 2,
  },
  {
    OBJECTID: 32,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 3,
    Shape_Length: 105.284706,
    sampleId: 1,
  },
  {
    OBJECTID: 34,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 3,
    Shape_Length: 105.13688,
    sampleId: 2,
  },
  {
    OBJECTID: 36,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 1,
    Shape_Length: 106.13279,
    sampleId: 1,
  },
  {
    OBJECTID: 38,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 2,
    Shape_Length: 102.44567,
    sampleId: 1,
  },
  {
    OBJECTID: 39,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 2,
    Shape_Length: 106.80636,
    sampleId: 2,
  },
  {
    OBJECTID: 42,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 1,
    Shape_Length: 102.55434,
    sampleId: 2,
  },
  {
    OBJECTID: 46,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 2,
    Shape_Length: 98.40856,
    sampleId: 1,
  },
  {
    OBJECTID: 48,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 2,
    Shape_Length: 99.51727,
    sampleId: 2,
  },
  {
    OBJECTID: 50,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 1,
    Shape_Length: 112.69274,
    sampleId: 1,
  },
  {
    OBJECTID: 52,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 1,
    Shape_Length: 110.261826,
    sampleId: 2,
  },
  {
    OBJECTID: 54,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 2,
    Shape_Length: 105.56833,
    sampleId: 1,
  },
  {
    OBJECTID: 56,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 2,
    Shape_Length: 96.85625,
    sampleId: 1,
  },
  {
    OBJECTID: 58,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 2,
    Shape_Length: 106.14244,
    sampleId: 2,
  },
  {
    OBJECTID: 60,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 2,
    Shape_Length: 98.60341,
    sampleId: 2,
  },
  {
    OBJECTID: 62,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 4,
    Shape_Length: 114.192055,
    sampleId: 1,
  },
  {
    OBJECTID: 63,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 4,
    Shape_Length: 114.98116,
    sampleId: 2,
  },
  {
    OBJECTID: 64,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 2,
    Shape_Length: 103.37811,
    sampleId: 1,
  },
  {
    OBJECTID: 66,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 2,
    Shape_Length: 101.433235,
    sampleId: 2,
  },
  {
    OBJECTID: 70,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.62889,
    sampleId: 1,
  },
  {
    OBJECTID: 72,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.71852,
    sampleId: 2,
  },
  {
    OBJECTID: 74,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 1,
    Shape_Length: 107.99653,
    sampleId: 1,
  },
  {
    OBJECTID: 76,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 1,
    Shape_Length: 109.38534,
    sampleId: 2,
  },
  {
    OBJECTID: 77,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83486,
    sampleId: 51,
  },
  {
    OBJECTID: 78,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.834885,
    sampleId: 52,
  },
  {
    OBJECTID: 79,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83489,
    sampleId: 53,
  },
  {
    OBJECTID: 80,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83492,
    sampleId: 54,
  },
  {
    OBJECTID: 81,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83485,
    sampleId: 55,
  },
  {
    OBJECTID: 82,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83486,
    sampleId: 2,
  },
  {
    OBJECTID: 83,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.834946,
    sampleId: 3,
  },
  {
    OBJECTID: 84,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83488,
    sampleId: 4,
  },
  {
    OBJECTID: 85,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83486,
    sampleId: 5,
  },
  {
    OBJECTID: 86,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.834885,
    sampleId: 6,
  },
  {
    OBJECTID: 87,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.8349,
    sampleId: 7,
  },
  {
    OBJECTID: 88,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.8349,
    sampleId: 8,
  },
  {
    OBJECTID: 89,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83492,
    sampleId: 9,
  },
  {
    OBJECTID: 90,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83486,
    sampleId: 10,
  },
  {
    OBJECTID: 91,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.834915,
    sampleId: 11,
  },
  {
    OBJECTID: 92,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83486,
    sampleId: 12,
  },
  {
    OBJECTID: 93,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83488,
    sampleId: 13,
  },
  {
    OBJECTID: 94,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.834946,
    sampleId: 14,
  },
  {
    OBJECTID: 95,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.834885,
    sampleId: 15,
  },
  {
    OBJECTID: 96,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83487,
    sampleId: 16,
  },
  {
    OBJECTID: 97,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83494,
    sampleId: 17,
  },
  {
    OBJECTID: 98,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83484,
    sampleId: 18,
  },
  {
    OBJECTID: 99,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.834885,
    sampleId: 19,
  },
  {
    OBJECTID: 100,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.834946,
    sampleId: 20,
  },
  {
    OBJECTID: 101,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.8349,
    sampleId: 21,
  },
  {
    OBJECTID: 102,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83488,
    sampleId: 22,
  },
  {
    OBJECTID: 103,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83486,
    sampleId: 23,
  },
  {
    OBJECTID: 104,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83491,
    sampleId: 24,
  },
  {
    OBJECTID: 105,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 3,
    Shape_Length: 98.83491,
    sampleId: 25,
  },
  {
    OBJECTID: 106,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83676,
    sampleId: 26,
  },
  {
    OBJECTID: 107,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83676,
    sampleId: 27,
  },
  {
    OBJECTID: 108,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.836716,
    sampleId: 28,
  },
  {
    OBJECTID: 109,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83678,
    sampleId: 29,
  },
  {
    OBJECTID: 110,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.836784,
    sampleId: 30,
  },
  {
    OBJECTID: 111,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.836716,
    sampleId: 31,
  },
  {
    OBJECTID: 112,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83682,
    sampleId: 32,
  },
  {
    OBJECTID: 113,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.836754,
    sampleId: 33,
  },
  {
    OBJECTID: 114,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83675,
    sampleId: 34,
  },
  {
    OBJECTID: 115,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.836784,
    sampleId: 35,
  },
  {
    OBJECTID: 116,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83672,
    sampleId: 36,
  },
  {
    OBJECTID: 117,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83686,
    sampleId: 37,
  },
  {
    OBJECTID: 118,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83674,
    sampleId: 38,
  },
  {
    OBJECTID: 119,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.8367,
    sampleId: 39,
  },
  {
    OBJECTID: 120,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.836784,
    sampleId: 40,
  },
  {
    OBJECTID: 121,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83681,
    sampleId: 41,
  },
  {
    OBJECTID: 122,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.8367,
    sampleId: 42,
  },
  {
    OBJECTID: 123,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83682,
    sampleId: 43,
  },
  {
    OBJECTID: 124,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83675,
    sampleId: 44,
  },
  {
    OBJECTID: 125,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83672,
    sampleId: 45,
  },
  {
    OBJECTID: 126,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83686,
    sampleId: 46,
  },
  {
    OBJECTID: 127,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83669,
    sampleId: 47,
  },
  {
    OBJECTID: 128,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.836784,
    sampleId: 48,
  },
  {
    OBJECTID: 129,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.836784,
    sampleId: 49,
  },
  {
    OBJECTID: 130,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83674,
    sampleId: 56,
  },
  {
    OBJECTID: 131,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83679,
    sampleId: 57,
  },
  {
    OBJECTID: 132,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.836754,
    sampleId: 58,
  },
  {
    OBJECTID: 133,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83679,
    sampleId: 59,
  },
  {
    OBJECTID: 134,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 3,
    Shape_Length: 100.83675,
    sampleId: 60,
  },
  {
    OBJECTID: 135,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 2,
    Shape_Length: 96.85621,
    sampleId: 3,
  },
  {
    OBJECTID: 136,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 2,
    Shape_Length: 96.856255,
    sampleId: 4,
  },
  {
    OBJECTID: 137,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 2,
    Shape_Length: 96.856255,
    sampleId: 5,
  },
  {
    OBJECTID: 138,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 2,
    Shape_Length: 96.85622,
    sampleId: 6,
  },
  {
    OBJECTID: 139,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 2,
    Shape_Length: 96.85629,
    sampleId: 7,
  },
  {
    OBJECTID: 140,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 2,
    Shape_Length: 96.85626,
    sampleId: 8,
  },
  {
    OBJECTID: 141,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 2,
    Shape_Length: 96.856224,
    sampleId: 9,
  },
  {
    OBJECTID: 142,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 2,
    Shape_Length: 96.856255,
    sampleId: 10,
  },
  {
    OBJECTID: 143,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 2,
    Shape_Length: 98.60333,
    sampleId: 11,
  },
  {
    OBJECTID: 144,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 2,
    Shape_Length: 98.603355,
    sampleId: 12,
  },
  {
    OBJECTID: 145,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 2,
    Shape_Length: 98.603325,
    sampleId: 13,
  },
  {
    OBJECTID: 146,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 2,
    Shape_Length: 98.603355,
    sampleId: 14,
  },
  {
    OBJECTID: 147,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 2,
    Shape_Length: 98.60331,
    sampleId: 15,
  },
  {
    OBJECTID: 148,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 2,
    Shape_Length: 98.60336,
    sampleId: 16,
  },
  {
    OBJECTID: 149,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 2,
    Shape_Length: 98.60345,
    sampleId: 17,
  },
  {
    OBJECTID: 150,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 2,
    Shape_Length: 98.60331,
    sampleId: 18,
  },
  {
    OBJECTID: 151,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 1,
    Shape_Length: 110.261765,
    sampleId: 3,
  },
  {
    OBJECTID: 152,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 1,
    Shape_Length: 110.26183,
    sampleId: 4,
  },
  {
    OBJECTID: 153,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 1,
    Shape_Length: 110.26178,
    sampleId: 5,
  },
  {
    OBJECTID: 154,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 1,
    laneId: 10,
    sectionId: 1,
    Shape_Length: 110.26176,
    sampleId: 6,
  },
  {
    OBJECTID: 155,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 1,
    Shape_Length: 112.692696,
    sampleId: 7,
  },
  {
    OBJECTID: 156,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 1,
    Shape_Length: 112.69274,
    sampleId: 8,
  },
  {
    OBJECTID: 157,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 1,
    Shape_Length: 112.692726,
    sampleId: 9,
  },
  {
    OBJECTID: 158,
    roude_name: "Madinty",
    roadId: 5,
    cityId: 1,
    direction: 0,
    laneId: 9,
    sectionId: 1,
    Shape_Length: 112.69277,
    sampleId: 10,
  },
  {
    OBJECTID: 159,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.628845,
    sampleId: 3,
  },
  {
    OBJECTID: 160,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.628815,
    sampleId: 4,
  },
  {
    OBJECTID: 161,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.6289,
    sampleId: 5,
  },
  {
    OBJECTID: 162,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.6288,
    sampleId: 6,
  },
  {
    OBJECTID: 163,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.62882,
    sampleId: 7,
  },
  {
    OBJECTID: 164,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.628944,
    sampleId: 8,
  },
  {
    OBJECTID: 165,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.628784,
    sampleId: 9,
  },
  {
    OBJECTID: 166,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.62887,
    sampleId: 10,
  },
  {
    OBJECTID: 167,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.6289,
    sampleId: 11,
  },
  {
    OBJECTID: 168,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.628815,
    sampleId: 12,
  },
  {
    OBJECTID: 169,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.62888,
    sampleId: 13,
  },
  {
    OBJECTID: 170,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.62883,
    sampleId: 14,
  },
  {
    OBJECTID: 171,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.62882,
    sampleId: 15,
  },
  {
    OBJECTID: 172,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.62888,
    sampleId: 16,
  },
  {
    OBJECTID: 173,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 3,
    Shape_Length: 100.62886,
    sampleId: 17,
  },
  {
    OBJECTID: 174,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.71855,
    sampleId: 18,
  },
  {
    OBJECTID: 175,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.71859,
    sampleId: 19,
  },
  {
    OBJECTID: 176,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.7185,
    sampleId: 20,
  },
  {
    OBJECTID: 177,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.71856,
    sampleId: 21,
  },
  {
    OBJECTID: 178,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.71849,
    sampleId: 22,
  },
  {
    OBJECTID: 179,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.718575,
    sampleId: 23,
  },
  {
    OBJECTID: 180,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.718575,
    sampleId: 24,
  },
  {
    OBJECTID: 181,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.71848,
    sampleId: 25,
  },
  {
    OBJECTID: 182,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.71863,
    sampleId: 26,
  },
  {
    OBJECTID: 183,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.71851,
    sampleId: 27,
  },
  {
    OBJECTID: 184,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.71854,
    sampleId: 28,
  },
  {
    OBJECTID: 185,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.71859,
    sampleId: 29,
  },
  {
    OBJECTID: 186,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.718475,
    sampleId: 30,
  },
  {
    OBJECTID: 187,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.71853,
    sampleId: 31,
  },
  {
    OBJECTID: 188,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 3,
    Shape_Length: 100.718575,
    sampleId: 32,
  },
  {
    OBJECTID: 189,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 2,
    Shape_Length: 99.51738,
    sampleId: 3,
  },
  {
    OBJECTID: 190,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 2,
    Shape_Length: 99.51735,
    sampleId: 4,
  },
  {
    OBJECTID: 191,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 2,
    Shape_Length: 99.51732,
    sampleId: 5,
  },
  {
    OBJECTID: 192,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 2,
    Shape_Length: 99.51735,
    sampleId: 6,
  },
  {
    OBJECTID: 193,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 2,
    Shape_Length: 99.51733,
    sampleId: 7,
  },
  {
    OBJECTID: 194,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 2,
    Shape_Length: 99.517265,
    sampleId: 8,
  },
  {
    OBJECTID: 195,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 2,
    Shape_Length: 99.51729,
    sampleId: 9,
  },
  {
    OBJECTID: 196,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 2,
    Shape_Length: 99.517395,
    sampleId: 10,
  },
  {
    OBJECTID: 197,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 2,
    Shape_Length: 99.51729,
    sampleId: 11,
  },
  {
    OBJECTID: 198,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 2,
    Shape_Length: 99.517334,
    sampleId: 12,
  },
  {
    OBJECTID: 199,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 2,
    Shape_Length: 99.51731,
    sampleId: 13,
  },
  {
    OBJECTID: 200,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 2,
    Shape_Length: 99.51734,
    sampleId: 14,
  },
  {
    OBJECTID: 201,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 2,
    Shape_Length: 98.40856,
    sampleId: 15,
  },
  {
    OBJECTID: 202,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 2,
    Shape_Length: 98.408516,
    sampleId: 16,
  },
  {
    OBJECTID: 203,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 2,
    Shape_Length: 98.40855,
    sampleId: 17,
  },
  {
    OBJECTID: 204,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 2,
    Shape_Length: 98.408554,
    sampleId: 18,
  },
  {
    OBJECTID: 205,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 2,
    Shape_Length: 98.408615,
    sampleId: 19,
  },
  {
    OBJECTID: 206,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 2,
    Shape_Length: 98.40852,
    sampleId: 20,
  },
  {
    OBJECTID: 207,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 2,
    Shape_Length: 98.40856,
    sampleId: 21,
  },
  {
    OBJECTID: 208,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 2,
    Shape_Length: 98.408554,
    sampleId: 22,
  },
  {
    OBJECTID: 209,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 2,
    Shape_Length: 98.40856,
    sampleId: 23,
  },
  {
    OBJECTID: 210,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 2,
    Shape_Length: 98.40852,
    sampleId: 24,
  },
  {
    OBJECTID: 211,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 2,
    Shape_Length: 98.4086,
    sampleId: 25,
  },
  {
    OBJECTID: 212,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 2,
    Shape_Length: 98.40855,
    sampleId: 26,
  },
  {
    OBJECTID: 213,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 2,
    Shape_Length: 100.03744,
    sampleId: 3,
  },
  {
    OBJECTID: 214,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 2,
    Shape_Length: 100.03751,
    sampleId: 4,
  },
  {
    OBJECTID: 215,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 2,
    Shape_Length: 100.03745,
    sampleId: 5,
  },
  {
    OBJECTID: 216,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 2,
    Shape_Length: 100.037506,
    sampleId: 6,
  },
  {
    OBJECTID: 217,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 2,
    Shape_Length: 100.03746,
    sampleId: 7,
  },
  {
    OBJECTID: 218,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 2,
    Shape_Length: 100.03742,
    sampleId: 8,
  },
  {
    OBJECTID: 219,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 2,
    Shape_Length: 100.03742,
    sampleId: 9,
  },
  {
    OBJECTID: 220,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 2,
    Shape_Length: 100.03746,
    sampleId: 10,
  },
  {
    OBJECTID: 221,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 2,
    Shape_Length: 100.037544,
    sampleId: 11,
  },
  {
    OBJECTID: 222,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 2,
    Shape_Length: 100.03741,
    sampleId: 12,
  },
  {
    OBJECTID: 223,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 2,
    Shape_Length: 100.03749,
    sampleId: 13,
  },
  {
    OBJECTID: 224,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 2,
    Shape_Length: 100.205505,
    sampleId: 14,
  },
  {
    OBJECTID: 225,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 2,
    Shape_Length: 100.20554,
    sampleId: 15,
  },
  {
    OBJECTID: 226,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 2,
    Shape_Length: 100.205505,
    sampleId: 16,
  },
  {
    OBJECTID: 227,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 2,
    Shape_Length: 100.20554,
    sampleId: 17,
  },
  {
    OBJECTID: 228,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 2,
    Shape_Length: 100.20557,
    sampleId: 18,
  },
  {
    OBJECTID: 229,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 2,
    Shape_Length: 100.20554,
    sampleId: 19,
  },
  {
    OBJECTID: 230,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 2,
    Shape_Length: 100.20548,
    sampleId: 20,
  },
  {
    OBJECTID: 231,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 2,
    Shape_Length: 100.20554,
    sampleId: 21,
  },
  {
    OBJECTID: 232,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 2,
    Shape_Length: 100.205536,
    sampleId: 22,
  },
  {
    OBJECTID: 233,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 2,
    Shape_Length: 100.20554,
    sampleId: 23,
  },
  {
    OBJECTID: 234,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 2,
    Shape_Length: 100.205505,
    sampleId: 24,
  },
  {
    OBJECTID: 235,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.144485,
    sampleId: 3,
  },
  {
    OBJECTID: 236,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.1444,
    sampleId: 4,
  },
  {
    OBJECTID: 237,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.14446,
    sampleId: 5,
  },
  {
    OBJECTID: 238,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.14437,
    sampleId: 6,
  },
  {
    OBJECTID: 239,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.14442,
    sampleId: 7,
  },
  {
    OBJECTID: 240,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.14444,
    sampleId: 8,
  },
  {
    OBJECTID: 241,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.1444,
    sampleId: 9,
  },
  {
    OBJECTID: 242,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.14449,
    sampleId: 10,
  },
  {
    OBJECTID: 243,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.144394,
    sampleId: 11,
  },
  {
    OBJECTID: 244,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.14445,
    sampleId: 12,
  },
  {
    OBJECTID: 245,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.14447,
    sampleId: 13,
  },
  {
    OBJECTID: 246,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.14437,
    sampleId: 14,
  },
  {
    OBJECTID: 247,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.14444,
    sampleId: 15,
  },
  {
    OBJECTID: 248,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.14442,
    sampleId: 16,
  },
  {
    OBJECTID: 249,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.14447,
    sampleId: 17,
  },
  {
    OBJECTID: 250,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 104.144394,
    sampleId: 18,
  },
  {
    OBJECTID: 251,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.61013,
    sampleId: 19,
  },
  {
    OBJECTID: 252,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.61021,
    sampleId: 20,
  },
  {
    OBJECTID: 253,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.61021,
    sampleId: 21,
  },
  {
    OBJECTID: 254,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.61012,
    sampleId: 22,
  },
  {
    OBJECTID: 255,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.61014,
    sampleId: 23,
  },
  {
    OBJECTID: 256,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.61018,
    sampleId: 24,
  },
  {
    OBJECTID: 257,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.61022,
    sampleId: 25,
  },
  {
    OBJECTID: 258,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.61018,
    sampleId: 26,
  },
  {
    OBJECTID: 259,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.6102,
    sampleId: 27,
  },
  {
    OBJECTID: 260,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.610115,
    sampleId: 28,
  },
  {
    OBJECTID: 261,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.61016,
    sampleId: 29,
  },
  {
    OBJECTID: 262,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.61021,
    sampleId: 30,
  },
  {
    OBJECTID: 263,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.610115,
    sampleId: 31,
  },
  {
    OBJECTID: 264,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.6102,
    sampleId: 32,
  },
  {
    OBJECTID: 265,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.61015,
    sampleId: 33,
  },
  {
    OBJECTID: 266,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 103.61021,
    sampleId: 34,
  },
  {
    OBJECTID: 267,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 2,
    Shape_Length: 102.44568,
    sampleId: 3,
  },
  {
    OBJECTID: 268,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 2,
    Shape_Length: 102.44577,
    sampleId: 4,
  },
  {
    OBJECTID: 269,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 2,
    Shape_Length: 102.44567,
    sampleId: 5,
  },
  {
    OBJECTID: 270,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 2,
    Shape_Length: 102.44567,
    sampleId: 6,
  },
  {
    OBJECTID: 271,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 2,
    Shape_Length: 102.4457,
    sampleId: 7,
  },
  {
    OBJECTID: 272,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 2,
    Shape_Length: 102.445755,
    sampleId: 8,
  },
  {
    OBJECTID: 273,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 2,
    Shape_Length: 102.44566,
    sampleId: 9,
  },
  {
    OBJECTID: 274,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 2,
    Shape_Length: 106.80646,
    sampleId: 10,
  },
  {
    OBJECTID: 275,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 2,
    Shape_Length: 106.80639,
    sampleId: 11,
  },
  {
    OBJECTID: 276,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 2,
    Shape_Length: 106.806335,
    sampleId: 12,
  },
  {
    OBJECTID: 277,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 2,
    Shape_Length: 106.806404,
    sampleId: 13,
  },
  {
    OBJECTID: 278,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 2,
    Shape_Length: 106.80643,
    sampleId: 14,
  },
  {
    OBJECTID: 279,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 2,
    Shape_Length: 106.80636,
    sampleId: 15,
  },
  {
    OBJECTID: 280,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 2,
    Shape_Length: 106.80641,
    sampleId: 16,
  },
  {
    OBJECTID: 281,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 3,
    Shape_Length: 105.28472,
    sampleId: 3,
  },
  {
    OBJECTID: 282,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 3,
    Shape_Length: 105.28475,
    sampleId: 4,
  },
  {
    OBJECTID: 283,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 3,
    Shape_Length: 105.28465,
    sampleId: 5,
  },
  {
    OBJECTID: 284,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 3,
    Shape_Length: 105.28469,
    sampleId: 6,
  },
  {
    OBJECTID: 285,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 3,
    Shape_Length: 105.284706,
    sampleId: 7,
  },
  {
    OBJECTID: 286,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 3,
    Shape_Length: 105.28473,
    sampleId: 8,
  },
  {
    OBJECTID: 287,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 3,
    Shape_Length: 105.28474,
    sampleId: 9,
  },
  {
    OBJECTID: 288,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 3,
    Shape_Length: 105.28475,
    sampleId: 10,
  },
  {
    OBJECTID: 289,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 3,
    Shape_Length: 105.28465,
    sampleId: 11,
  },
  {
    OBJECTID: 290,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 3,
    Shape_Length: 105.28467,
    sampleId: 12,
  },
  {
    OBJECTID: 291,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 3,
    Shape_Length: 105.28476,
    sampleId: 13,
  },
  {
    OBJECTID: 292,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 3,
    Shape_Length: 105.136826,
    sampleId: 14,
  },
  {
    OBJECTID: 293,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 3,
    Shape_Length: 105.1369,
    sampleId: 15,
  },
  {
    OBJECTID: 294,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 3,
    Shape_Length: 105.136894,
    sampleId: 16,
  },
  {
    OBJECTID: 295,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 3,
    Shape_Length: 105.136826,
    sampleId: 17,
  },
  {
    OBJECTID: 296,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 3,
    Shape_Length: 105.13689,
    sampleId: 18,
  },
  {
    OBJECTID: 297,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 3,
    Shape_Length: 105.13683,
    sampleId: 19,
  },
  {
    OBJECTID: 298,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 3,
    Shape_Length: 105.13689,
    sampleId: 20,
  },
  {
    OBJECTID: 299,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 3,
    Shape_Length: 105.13691,
    sampleId: 21,
  },
  {
    OBJECTID: 300,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 3,
    Shape_Length: 105.136826,
    sampleId: 22,
  },
  {
    OBJECTID: 301,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 3,
    Shape_Length: 105.13688,
    sampleId: 23,
  },
  {
    OBJECTID: 302,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 3,
    Shape_Length: 105.13685,
    sampleId: 24,
  },
  {
    OBJECTID: 303,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 1,
    Shape_Length: 107.53817,
    sampleId: 3,
  },
  {
    OBJECTID: 304,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 1,
    Shape_Length: 107.53824,
    sampleId: 4,
  },
  {
    OBJECTID: 305,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 1,
    laneId: 6,
    sectionId: 1,
    Shape_Length: 107.53816,
    sampleId: 5,
  },
  {
    OBJECTID: 306,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 1,
    Shape_Length: 107.120026,
    sampleId: 6,
  },
  {
    OBJECTID: 307,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 1,
    Shape_Length: 107.119934,
    sampleId: 7,
  },
  {
    OBJECTID: 308,
    roude_name: "Alzohor",
    roadId: 3,
    cityId: 1,
    direction: 0,
    laneId: 5,
    sectionId: 1,
    Shape_Length: 107.120026,
    sampleId: 8,
  },
  {
    OBJECTID: 309,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 1,
    Shape_Length: 102.55435,
    sampleId: 3,
  },
  {
    OBJECTID: 310,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 1,
    Shape_Length: 102.55433,
    sampleId: 4,
  },
  {
    OBJECTID: 311,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 1,
    Shape_Length: 102.55437,
    sampleId: 5,
  },
  {
    OBJECTID: 312,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 1,
    Shape_Length: 106.13282,
    sampleId: 6,
  },
  {
    OBJECTID: 313,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 1,
    Shape_Length: 106.132866,
    sampleId: 7,
  },
  {
    OBJECTID: 314,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 1,
    Shape_Length: 106.1328,
    sampleId: 8,
  },
  {
    OBJECTID: 315,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.83843,
    sampleId: 3,
  },
  {
    OBJECTID: 316,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.83845,
    sampleId: 4,
  },
  {
    OBJECTID: 317,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.83839,
    sampleId: 5,
  },
  {
    OBJECTID: 318,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.838356,
    sampleId: 6,
  },
  {
    OBJECTID: 319,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.8384,
    sampleId: 7,
  },
  {
    OBJECTID: 320,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.83842,
    sampleId: 8,
  },
  {
    OBJECTID: 321,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.8384,
    sampleId: 9,
  },
  {
    OBJECTID: 322,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.8384,
    sampleId: 10,
  },
  {
    OBJECTID: 323,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.83836,
    sampleId: 11,
  },
  {
    OBJECTID: 324,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.83842,
    sampleId: 12,
  },
  {
    OBJECTID: 325,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.83846,
    sampleId: 13,
  },
  {
    OBJECTID: 326,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.83835,
    sampleId: 14,
  },
  {
    OBJECTID: 327,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.8384,
    sampleId: 15,
  },
  {
    OBJECTID: 328,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.83845,
    sampleId: 16,
  },
  {
    OBJECTID: 329,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.838356,
    sampleId: 17,
  },
  {
    OBJECTID: 330,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.838455,
    sampleId: 18,
  },
  {
    OBJECTID: 331,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.83835,
    sampleId: 19,
  },
  {
    OBJECTID: 332,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.838455,
    sampleId: 20,
  },
  {
    OBJECTID: 333,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.838356,
    sampleId: 21,
  },
  {
    OBJECTID: 334,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.838425,
    sampleId: 22,
  },
  {
    OBJECTID: 335,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 0,
    laneId: 1,
    sectionId: 1,
    Shape_Length: 102.83839,
    sampleId: 23,
  },
  {
    OBJECTID: 336,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42741,
    sampleId: 24,
  },
  {
    OBJECTID: 337,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42734,
    sampleId: 25,
  },
  {
    OBJECTID: 338,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42733,
    sampleId: 26,
  },
  {
    OBJECTID: 339,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42738,
    sampleId: 27,
  },
  {
    OBJECTID: 340,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42729,
    sampleId: 28,
  },
  {
    OBJECTID: 341,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.4274,
    sampleId: 29,
  },
  {
    OBJECTID: 342,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42734,
    sampleId: 30,
  },
  {
    OBJECTID: 343,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42732,
    sampleId: 31,
  },
  {
    OBJECTID: 344,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42741,
    sampleId: 32,
  },
  {
    OBJECTID: 345,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.427345,
    sampleId: 33,
  },
  {
    OBJECTID: 346,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42735,
    sampleId: 34,
  },
  {
    OBJECTID: 347,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.427376,
    sampleId: 35,
  },
  {
    OBJECTID: 348,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.427284,
    sampleId: 36,
  },
  {
    OBJECTID: 349,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42736,
    sampleId: 37,
  },
  {
    OBJECTID: 350,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.4274,
    sampleId: 38,
  },
  {
    OBJECTID: 351,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42736,
    sampleId: 39,
  },
  {
    OBJECTID: 352,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42733,
    sampleId: 40,
  },
  {
    OBJECTID: 353,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42735,
    sampleId: 41,
  },
  {
    OBJECTID: 354,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.42737,
    sampleId: 42,
  },
  {
    OBJECTID: 355,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.4273,
    sampleId: 43,
  },
  {
    OBJECTID: 356,
    roude_name: "Talaat Mostafa",
    roadId: 1,
    cityId: 1,
    direction: 1,
    laneId: 2,
    sectionId: 1,
    Shape_Length: 102.427376,
    sampleId: 44,
  },
  {
    OBJECTID: 357,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 1,
    Shape_Length: 100.74726,
    sampleId: 3,
  },
  {
    OBJECTID: 358,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 1,
    Shape_Length: 100.74727,
    sampleId: 4,
  },
  {
    OBJECTID: 359,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 1,
    Shape_Length: 100.747185,
    sampleId: 5,
  },
  {
    OBJECTID: 360,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 1,
    Shape_Length: 100.747246,
    sampleId: 6,
  },
  {
    OBJECTID: 361,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 1,
    Shape_Length: 100.747284,
    sampleId: 7,
  },
  {
    OBJECTID: 362,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 1,
    Shape_Length: 100.74721,
    sampleId: 8,
  },
  {
    OBJECTID: 363,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 1,
    Shape_Length: 100.74721,
    sampleId: 9,
  },
  {
    OBJECTID: 364,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 1,
    Shape_Length: 100.74724,
    sampleId: 10,
  },
  {
    OBJECTID: 365,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 1,
    Shape_Length: 100.7473,
    sampleId: 11,
  },
  {
    OBJECTID: 366,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 1,
    Shape_Length: 100.747215,
    sampleId: 12,
  },
  {
    OBJECTID: 367,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 1,
    Shape_Length: 100.26474,
    sampleId: 13,
  },
  {
    OBJECTID: 368,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 1,
    Shape_Length: 100.26475,
    sampleId: 14,
  },
  {
    OBJECTID: 369,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 1,
    Shape_Length: 100.26465,
    sampleId: 15,
  },
  {
    OBJECTID: 370,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 1,
    Shape_Length: 100.26467,
    sampleId: 16,
  },
  {
    OBJECTID: 371,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 1,
    Shape_Length: 100.26471,
    sampleId: 17,
  },
  {
    OBJECTID: 372,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 1,
    Shape_Length: 100.26475,
    sampleId: 18,
  },
  {
    OBJECTID: 373,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 1,
    Shape_Length: 100.264725,
    sampleId: 19,
  },
  {
    OBJECTID: 374,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 1,
    Shape_Length: 100.26467,
    sampleId: 20,
  },
  {
    OBJECTID: 375,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 1,
    Shape_Length: 100.26476,
    sampleId: 21,
  },
  {
    OBJECTID: 376,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 1,
    Shape_Length: 100.26466,
    sampleId: 22,
  },
  {
    OBJECTID: 377,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 2,
    Shape_Length: 105.56825,
    sampleId: 3,
  },
  {
    OBJECTID: 378,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 2,
    Shape_Length: 105.56829,
    sampleId: 4,
  },
  {
    OBJECTID: 379,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 2,
    Shape_Length: 105.5682,
    sampleId: 5,
  },
  {
    OBJECTID: 380,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 2,
    Shape_Length: 105.568344,
    sampleId: 6,
  },
  {
    OBJECTID: 381,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 2,
    Shape_Length: 105.568245,
    sampleId: 7,
  },
  {
    OBJECTID: 382,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 2,
    Shape_Length: 105.56826,
    sampleId: 8,
  },
  {
    OBJECTID: 383,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 2,
    Shape_Length: 105.56831,
    sampleId: 9,
  },
  {
    OBJECTID: 384,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 2,
    Shape_Length: 105.56829,
    sampleId: 10,
  },
  {
    OBJECTID: 385,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 2,
    Shape_Length: 105.568275,
    sampleId: 11,
  },
  {
    OBJECTID: 386,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 2,
    Shape_Length: 105.568275,
    sampleId: 12,
  },
  {
    OBJECTID: 387,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 2,
    Shape_Length: 105.56829,
    sampleId: 13,
  },
  {
    OBJECTID: 388,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 2,
    Shape_Length: 106.142365,
    sampleId: 14,
  },
  {
    OBJECTID: 389,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 2,
    Shape_Length: 106.142365,
    sampleId: 15,
  },
  {
    OBJECTID: 390,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 2,
    Shape_Length: 106.14244,
    sampleId: 16,
  },
  {
    OBJECTID: 391,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 2,
    Shape_Length: 106.14239,
    sampleId: 17,
  },
  {
    OBJECTID: 392,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 2,
    Shape_Length: 106.14233,
    sampleId: 18,
  },
  {
    OBJECTID: 393,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 2,
    Shape_Length: 106.14249,
    sampleId: 19,
  },
  {
    OBJECTID: 394,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 2,
    Shape_Length: 106.14233,
    sampleId: 20,
  },
  {
    OBJECTID: 395,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 2,
    Shape_Length: 106.14243,
    sampleId: 21,
  },
  {
    OBJECTID: 396,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 2,
    Shape_Length: 106.14242,
    sampleId: 22,
  },
  {
    OBJECTID: 397,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 2,
    Shape_Length: 106.14238,
    sampleId: 23,
  },
  {
    OBJECTID: 398,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 2,
    Shape_Length: 106.14238,
    sampleId: 24,
  },
  {
    OBJECTID: 399,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 3,
    Shape_Length: 98.642166,
    sampleId: 3,
  },
  {
    OBJECTID: 400,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 3,
    Shape_Length: 98.642204,
    sampleId: 4,
  },
  {
    OBJECTID: 401,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 3,
    Shape_Length: 98.642204,
    sampleId: 5,
  },
  {
    OBJECTID: 402,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 3,
    Shape_Length: 98.64208,
    sampleId: 6,
  },
  {
    OBJECTID: 403,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 3,
    Shape_Length: 98.64226,
    sampleId: 7,
  },
  {
    OBJECTID: 404,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 3,
    Shape_Length: 98.6422,
    sampleId: 8,
  },
  {
    OBJECTID: 405,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 3,
    Shape_Length: 98.64216,
    sampleId: 9,
  },
  {
    OBJECTID: 406,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 3,
    Shape_Length: 98.64213,
    sampleId: 10,
  },
  {
    OBJECTID: 407,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 3,
    Shape_Length: 98.64214,
    sampleId: 11,
  },
  {
    OBJECTID: 408,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 3,
    Shape_Length: 98.64223,
    sampleId: 12,
  },
  {
    OBJECTID: 409,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 3,
    Shape_Length: 98.64222,
    sampleId: 13,
  },
  {
    OBJECTID: 410,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 3,
    Shape_Length: 98.642136,
    sampleId: 14,
  },
  {
    OBJECTID: 411,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 3,
    Shape_Length: 98.3188,
    sampleId: 15,
  },
  {
    OBJECTID: 412,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 3,
    Shape_Length: 98.31888,
    sampleId: 16,
  },
  {
    OBJECTID: 413,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 3,
    Shape_Length: 98.318756,
    sampleId: 17,
  },
  {
    OBJECTID: 414,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 3,
    Shape_Length: 98.318886,
    sampleId: 18,
  },
  {
    OBJECTID: 415,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 3,
    Shape_Length: 98.31877,
    sampleId: 19,
  },
  {
    OBJECTID: 416,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 3,
    Shape_Length: 98.31882,
    sampleId: 20,
  },
  {
    OBJECTID: 417,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 3,
    Shape_Length: 98.318825,
    sampleId: 21,
  },
  {
    OBJECTID: 418,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 3,
    Shape_Length: 98.31885,
    sampleId: 22,
  },
  {
    OBJECTID: 419,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 3,
    Shape_Length: 98.31883,
    sampleId: 23,
  },
  {
    OBJECTID: 420,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 3,
    Shape_Length: 98.3188,
    sampleId: 24,
  },
  {
    OBJECTID: 421,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 3,
    Shape_Length: 98.31889,
    sampleId: 25,
  },
  {
    OBJECTID: 422,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 3,
    Shape_Length: 98.318794,
    sampleId: 26,
  },
  {
    OBJECTID: 423,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 4,
    Shape_Length: 114.98113,
    sampleId: 3,
  },
  {
    OBJECTID: 424,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 4,
    Shape_Length: 114.98108,
    sampleId: 4,
  },
  {
    OBJECTID: 425,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 1,
    laneId: 8,
    sectionId: 4,
    Shape_Length: 114.9812,
    sampleId: 5,
  },
  {
    OBJECTID: 426,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 4,
    Shape_Length: 114.19212,
    sampleId: 6,
  },
  {
    OBJECTID: 427,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 4,
    Shape_Length: 114.19215,
    sampleId: 7,
  },
  {
    OBJECTID: 428,
    roude_name: "Alrabea",
    roadId: 4,
    cityId: 1,
    direction: 0,
    laneId: 7,
    sectionId: 4,
    Shape_Length: 114.19209,
    sampleId: 8,
  },
  {
    OBJECTID: 429,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.57178,
    sampleId: 2,
  },
  {
    OBJECTID: 430,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.57182,
    sampleId: 3,
  },
  {
    OBJECTID: 431,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.57179,
    sampleId: 4,
  },
  {
    OBJECTID: 432,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.57182,
    sampleId: 5,
  },
  {
    OBJECTID: 433,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.571754,
    sampleId: 6,
  },
  {
    OBJECTID: 434,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.57185,
    sampleId: 7,
  },
  {
    OBJECTID: 435,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.5718,
    sampleId: 9,
  },
  {
    OBJECTID: 436,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.57179,
    sampleId: 11,
  },
  {
    OBJECTID: 437,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.5718,
    sampleId: 12,
  },
  {
    OBJECTID: 438,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.57175,
    sampleId: 13,
  },
  {
    OBJECTID: 439,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.57183,
    sampleId: 14,
  },
  {
    OBJECTID: 440,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.57175,
    sampleId: 15,
  },
  {
    OBJECTID: 441,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.57184,
    sampleId: 16,
  },
  {
    OBJECTID: 442,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.571754,
    sampleId: 17,
  },
  {
    OBJECTID: 443,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.571846,
    sampleId: 18,
  },
  {
    OBJECTID: 444,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.571785,
    sampleId: 19,
  },
  {
    OBJECTID: 445,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.57176,
    sampleId: 20,
  },
  {
    OBJECTID: 446,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.571815,
    sampleId: 21,
  },
  {
    OBJECTID: 447,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.571846,
    sampleId: 22,
  },
  {
    OBJECTID: 448,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 0,
    laneId: 3,
    sectionId: 4,
    Shape_Length: 100.571754,
    sampleId: 23,
  },
  {
    OBJECTID: 449,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.303825,
    sampleId: 24,
  },
  {
    OBJECTID: 450,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.30383,
    sampleId: 25,
  },
  {
    OBJECTID: 451,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.30386,
    sampleId: 26,
  },
  {
    OBJECTID: 452,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.3038,
    sampleId: 27,
  },
  {
    OBJECTID: 453,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.30384,
    sampleId: 28,
  },
  {
    OBJECTID: 454,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.30385,
    sampleId: 29,
  },
  {
    OBJECTID: 455,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.30383,
    sampleId: 30,
  },
  {
    OBJECTID: 456,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.303795,
    sampleId: 31,
  },
  {
    OBJECTID: 457,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.30385,
    sampleId: 32,
  },
  {
    OBJECTID: 458,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.303795,
    sampleId: 33,
  },
  {
    OBJECTID: 459,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.303856,
    sampleId: 34,
  },
  {
    OBJECTID: 460,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.30379,
    sampleId: 35,
  },
  {
    OBJECTID: 461,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.3038,
    sampleId: 8,
  },
  {
    OBJECTID: 462,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.3038,
    sampleId: 10,
  },
  {
    OBJECTID: 463,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.30388,
    sampleId: 11,
  },
  {
    OBJECTID: 464,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.30386,
    sampleId: 12,
  },
  {
    OBJECTID: 465,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.30376,
    sampleId: 13,
  },
  {
    OBJECTID: 466,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.30383,
    sampleId: 14,
  },
  {
    OBJECTID: 467,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.3038,
    sampleId: 15,
  },
  {
    OBJECTID: 468,
    roude_name: "Alwady",
    roadId: 2,
    cityId: 1,
    direction: 1,
    laneId: 4,
    sectionId: 4,
    Shape_Length: 100.30385,
    sampleId: 16,
  },
  {
    OBJECTID: 469,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 1,
    Shape_Length: 107.996414,
    sampleId: 3,
  },
  {
    OBJECTID: 470,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 1,
    Shape_Length: 107.99654,
    sampleId: 4,
  },
  {
    OBJECTID: 471,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 1,
    Shape_Length: 107.99645,
    sampleId: 5,
  },
  {
    OBJECTID: 472,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 1,
    Shape_Length: 107.99649,
    sampleId: 6,
  },
  {
    OBJECTID: 473,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 1,
    Shape_Length: 107.99657,
    sampleId: 7,
  },
  {
    OBJECTID: 474,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 1,
    Shape_Length: 107.99643,
    sampleId: 8,
  },
  {
    OBJECTID: 475,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 1,
    Shape_Length: 109.38531,
    sampleId: 9,
  },
  {
    OBJECTID: 476,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 1,
    Shape_Length: 109.385254,
    sampleId: 10,
  },
  {
    OBJECTID: 477,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 1,
    Shape_Length: 109.38534,
    sampleId: 11,
  },
  {
    OBJECTID: 478,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 1,
    Shape_Length: 109.38531,
    sampleId: 12,
  },
  {
    OBJECTID: 479,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 1,
    Shape_Length: 109.38531,
    sampleId: 13,
  },
  {
    OBJECTID: 480,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 1,
    Shape_Length: 109.385315,
    sampleId: 14,
  },
  {
    OBJECTID: 481,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 2,
    Shape_Length: 101.433266,
    sampleId: 3,
  },
  {
    OBJECTID: 482,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 2,
    Shape_Length: 101.43326,
    sampleId: 4,
  },
  {
    OBJECTID: 483,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 2,
    Shape_Length: 101.433266,
    sampleId: 5,
  },
  {
    OBJECTID: 484,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 2,
    Shape_Length: 101.43327,
    sampleId: 6,
  },
  {
    OBJECTID: 485,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 2,
    Shape_Length: 101.43333,
    sampleId: 7,
  },
  {
    OBJECTID: 486,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 2,
    Shape_Length: 101.43321,
    sampleId: 8,
  },
  {
    OBJECTID: 487,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 2,
    Shape_Length: 101.433304,
    sampleId: 9,
  },
  {
    OBJECTID: 488,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 2,
    Shape_Length: 103.37819,
    sampleId: 10,
  },
  {
    OBJECTID: 489,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 2,
    Shape_Length: 103.37815,
    sampleId: 11,
  },
  {
    OBJECTID: 490,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 2,
    Shape_Length: 103.37819,
    sampleId: 12,
  },
  {
    OBJECTID: 491,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 2,
    Shape_Length: 103.37816,
    sampleId: 13,
  },
  {
    OBJECTID: 492,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 2,
    Shape_Length: 103.37817,
    sampleId: 14,
  },
  {
    OBJECTID: 493,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 2,
    Shape_Length: 103.37809,
    sampleId: 15,
  },
  {
    OBJECTID: 494,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 2,
    Shape_Length: 103.378204,
    sampleId: 16,
  },
  {
    OBJECTID: 495,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.814,
    sampleId: 3,
  },
  {
    OBJECTID: 496,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.81396,
    sampleId: 4,
  },
  {
    OBJECTID: 497,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.81398,
    sampleId: 5,
  },
  {
    OBJECTID: 498,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.814,
    sampleId: 6,
  },
  {
    OBJECTID: 499,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.814,
    sampleId: 7,
  },
  {
    OBJECTID: 500,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.81399,
    sampleId: 8,
  },
  {
    OBJECTID: 501,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.81396,
    sampleId: 9,
  },
  {
    OBJECTID: 502,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.81404,
    sampleId: 10,
  },
  {
    OBJECTID: 503,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.81394,
    sampleId: 11,
  },
  {
    OBJECTID: 504,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.81398,
    sampleId: 12,
  },
  {
    OBJECTID: 505,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.81403,
    sampleId: 13,
  },
  {
    OBJECTID: 506,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.81403,
    sampleId: 14,
  },
  {
    OBJECTID: 507,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.8139,
    sampleId: 15,
  },
  {
    OBJECTID: 508,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.81402,
    sampleId: 16,
  },
  {
    OBJECTID: 509,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.814026,
    sampleId: 17,
  },
  {
    OBJECTID: 510,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.81392,
    sampleId: 18,
  },
  {
    OBJECTID: 511,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.814,
    sampleId: 19,
  },
  {
    OBJECTID: 512,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.814026,
    sampleId: 20,
  },
  {
    OBJECTID: 513,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 0,
    laneId: 11,
    sectionId: 3,
    Shape_Length: 102.813995,
    sampleId: 21,
  },
  {
    OBJECTID: 514,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.45031,
    sampleId: 22,
  },
  {
    OBJECTID: 515,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.450325,
    sampleId: 23,
  },
  {
    OBJECTID: 516,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.450356,
    sampleId: 24,
  },
  {
    OBJECTID: 517,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.45026,
    sampleId: 25,
  },
  {
    OBJECTID: 518,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.45035,
    sampleId: 26,
  },
  {
    OBJECTID: 519,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.45036,
    sampleId: 27,
  },
  {
    OBJECTID: 520,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.450294,
    sampleId: 28,
  },
  {
    OBJECTID: 521,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.45026,
    sampleId: 29,
  },
  {
    OBJECTID: 522,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.45038,
    sampleId: 30,
  },
  {
    OBJECTID: 523,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.450325,
    sampleId: 31,
  },
  {
    OBJECTID: 524,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.45031,
    sampleId: 32,
  },
  {
    OBJECTID: 525,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.450294,
    sampleId: 33,
  },
  {
    OBJECTID: 526,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.450325,
    sampleId: 34,
  },
  {
    OBJECTID: 527,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.45038,
    sampleId: 35,
  },
  {
    OBJECTID: 528,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.450294,
    sampleId: 36,
  },
  {
    OBJECTID: 529,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.450386,
    sampleId: 37,
  },
  {
    OBJECTID: 530,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.45026,
    sampleId: 38,
  },
  {
    OBJECTID: 531,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.45037,
    sampleId: 39,
  },
  {
    OBJECTID: 532,
    roude_name: "Talaat Mostafa 2",
    roadId: 6,
    cityId: 1,
    direction: 1,
    laneId: 12,
    sectionId: 3,
    Shape_Length: 100.4503,
    sampleId: 40,
  },
];

export default Data;
